IF OBJECT_ID('CLIENTES') IS NULL
BEGIN
	CREATE TABLE CLIENTES
	(
		CLIENTE_ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
		NOME VARCHAR(50) NULL,
		ENDERECO VARCHAR(250) NULL,
		CIDADE VARCHAR(250) NULL,
		BAIRRO VARCHAR(100) NULL,
		ESTADO VARCHAR(2) NULL,
		CEP VARCHAR(10) NULL,
		TELEFONE VARCHAR(14) NULL,
		EMAIL VARCHAR(250) NULL,
		DATA_NASCIMENTO DATETIME NULL
	)
END

IF OBJECT_ID('USUARIOS') IS NULL
BEGIN
	CREATE TABLE USUARIOS
	(
		USUARIO_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOME VARCHAR(50) NOT NULL,
		SENHA VARCHAR(50) NOT NULL,		
	)
END

INSERT INTO USUARIOS(NOME, SENHA) VALUES ('MASTER', '123')